package defpackage;

import java.util.HashMap;
import java.util.Map;

/* renamed from: cxn reason: default package */
/* compiled from: ViewNameHashMap */
public final class cxn {
    public static final Map<String, String> a = new HashMap();
    private static int b = 1;

    static {
        Map<String, String> map = a;
        int i = b;
        b = i + 1;
        map.put("FrameLayout", Integer.toString(i, 36));
        Map<String, String> map2 = a;
        int i2 = b;
        b = i2 + 1;
        map2.put("RelativeLayout", Integer.toString(i2, 36));
        Map<String, String> map3 = a;
        int i3 = b;
        b = i3 + 1;
        map3.put("ListView", Integer.toString(i3, 36));
        Map<String, String> map4 = a;
        int i4 = b;
        b = i4 + 1;
        map4.put("Button", Integer.toString(i4, 36));
        Map<String, String> map5 = a;
        int i5 = b;
        b = i5 + 1;
        map5.put("ImageView", Integer.toString(i5, 36));
        Map<String, String> map6 = a;
        int i6 = b;
        b = i6 + 1;
        map6.put("EditText", Integer.toString(i6, 36));
        Map<String, String> map7 = a;
        int i7 = b;
        b = i7 + 1;
        map7.put("TextView", Integer.toString(i7, 36));
        Map<String, String> map8 = a;
        int i8 = b;
        b = i8 + 1;
        map8.put("LinearLayout", Integer.toString(i8, 36));
        Map<String, String> map9 = a;
        int i9 = b;
        b = i9 + 1;
        map9.put("ScrollView", Integer.toString(i9, 36));
        Map<String, String> map10 = a;
        int i10 = b;
        b = i10 + 1;
        map10.put("MapInteractiveRelativeLayout", Integer.toString(i10, 36));
        Map<String, String> map11 = a;
        int i11 = b;
        b = i11 + 1;
        map11.put("SearchEditor", Integer.toString(i11, 36));
        Map<String, String> map12 = a;
        int i12 = b;
        b = i12 + 1;
        map12.put("FocusableContainer", Integer.toString(i12, 36));
        Map<String, String> map13 = a;
        int i13 = b;
        b = i13 + 1;
        map13.put("SearchSuggListView", Integer.toString(i13, 36));
        Map<String, String> map14 = a;
        int i14 = b;
        b = i14 + 1;
        map14.put("LaterImageButton", Integer.toString(i14, 36));
        Map<String, String> map15 = a;
        int i15 = b;
        b = i15 + 1;
        map15.put("SuspendViewCommonTemplate", Integer.toString(i15, 36));
        Map<String, String> map16 = a;
        int i16 = b;
        b = i16 + 1;
        map16.put("ZoomView", Integer.toString(i16, 36));
        Map<String, String> map17 = a;
        int i17 = b;
        b = i17 + 1;
        map17.put("DrawableCenterTextView", Integer.toString(i17, 36));
        Map<String, String> map18 = a;
        int i18 = b;
        b = i18 + 1;
        map18.put("SearchPoiTipView", Integer.toString(i18, 36));
        Map<String, String> map19 = a;
        int i19 = b;
        b = i19 + 1;
        map19.put("PoiDetailSlidingView", Integer.toString(i19, 36));
        Map<String, String> map20 = a;
        int i20 = b;
        b = i20 + 1;
        map20.put("DialogRootView", Integer.toString(i20, 36));
        Map<String, String> map21 = a;
        int i21 = b;
        b = i21 + 1;
        map21.put("CheckBox", Integer.toString(i21, 36));
        Map<String, String> map22 = a;
        int i22 = b;
        b = i22 + 1;
        map22.put("NightModeImageView", Integer.toString(i22, 36));
        Map<String, String> map23 = a;
        int i23 = b;
        b = i23 + 1;
        map23.put("NightModeLinearLayout", Integer.toString(i23, 36));
        Map<String, String> map24 = a;
        int i24 = b;
        b = i24 + 1;
        map24.put("AdaptiveButton", Integer.toString(i24, 36));
        Map<String, String> map25 = a;
        int i25 = b;
        b = i25 + 1;
        map25.put("ActionBarOverlayLayout", Integer.toString(i25, 36));
        Map<String, String> map26 = a;
        int i26 = b;
        b = i26 + 1;
        map26.put("ImageButton", Integer.toString(i26, 36));
        Map<String, String> map27 = a;
        int i27 = b;
        b = i27 + 1;
        map27.put("ObservableScrollView", Integer.toString(i27, 36));
        Map<String, String> map28 = a;
        int i28 = b;
        b = i28 + 1;
        map28.put("TitleBar", Integer.toString(i28, 36));
        Map<String, String> map29 = a;
        int i29 = b;
        b = i29 + 1;
        map29.put("InterruptableRelativeLayout", Integer.toString(i29, 36));
        Map<String, String> map30 = a;
        int i30 = b;
        b = i30 + 1;
        map30.put("MineGridView", Integer.toString(i30, 36));
        Map<String, String> map31 = a;
        int i31 = b;
        b = i31 + 1;
        map31.put("ShpHotWordLayout", Integer.toString(i31, 36));
        Map<String, String> map32 = a;
        int i32 = b;
        b = i32 + 1;
        map32.put("SearchHistoryView", Integer.toString(i32, 36));
        Map<String, String> map33 = a;
        int i33 = b;
        b = i33 + 1;
        map33.put("MvpImageView", Integer.toString(i33, 36));
        Map<String, String> map34 = a;
        int i34 = b;
        b = i34 + 1;
        map34.put("MapLayerView", Integer.toString(i34, 36));
        Map<String, String> map35 = a;
        int i35 = b;
        b = i35 + 1;
        map35.put("GPSButton", Integer.toString(i35, 36));
        Map<String, String> map36 = a;
        int i36 = b;
        b = i36 + 1;
        map36.put("AnchorListView", Integer.toString(i36, 36));
        Map<String, String> map37 = a;
        int i37 = b;
        b = i37 + 1;
        map37.put("AnchorListWidget", Integer.toString(i37, 36));
        Map<String, String> map38 = a;
        int i38 = b;
        b = i38 + 1;
        map38.put("SearchEdit", Integer.toString(i38, 36));
        Map<String, String> map39 = a;
        int i39 = b;
        b = i39 + 1;
        map39.put("SearchResultHeaderView", Integer.toString(i39, 36));
        Map<String, String> map40 = a;
        int i40 = b;
        b = i40 + 1;
        map40.put("RevealFrameLayout", Integer.toString(i40, 36));
        Map<String, String> map41 = a;
        int i41 = b;
        b = i41 + 1;
        map41.put("MineEntryGridView", Integer.toString(i41, 36));
        Map<String, String> map42 = a;
        int i42 = b;
        b = i42 + 1;
        map42.put("LinearListView2", Integer.toString(i42, 36));
        Map<String, String> map43 = a;
        int i43 = b;
        b = i43 + 1;
        map43.put("InternalListViewSDK9", Integer.toString(i43, 36));
        Map<String, String> map44 = a;
        int i44 = b;
        b = i44 + 1;
        map44.put("RefreshViewFrame", Integer.toString(i44, 36));
        Map<String, String> map45 = a;
        int i45 = b;
        b = i45 + 1;
        map45.put("PullToRefreshListView", Integer.toString(i45, 36));
        Map<String, String> map46 = a;
        int i46 = b;
        b = i46 + 1;
        map46.put("NoSaveStateFrameLayout", Integer.toString(i46, 36));
        Map<String, String> map47 = a;
        int i47 = b;
        b = i47 + 1;
        map47.put("ViewPager", Integer.toString(i47, 36));
        Map<String, String> map48 = a;
        int i48 = b;
        b = i48 + 1;
        map48.put("SuspendPartitionView", Integer.toString(i48, 36));
        Map<String, String> map49 = a;
        int i49 = b;
        b = i49 + 1;
        map49.put("SuspendViewContainer", Integer.toString(i49, 36));
        Map<String, String> map50 = a;
        int i50 = b;
        b = i50 + 1;
        map50.put("HorizontalScrollView", Integer.toString(i50, 36));
        Map<String, String> map51 = a;
        int i51 = b;
        b = i51 + 1;
        map51.put("GridView", Integer.toString(i51, 36));
        Map<String, String> map52 = a;
        int i52 = b;
        b = i52 + 1;
        map52.put("DIYMainMapView", Integer.toString(i52, 36));
        Map<String, String> map53 = a;
        int i53 = b;
        b = i53 + 1;
        map53.put("RecyclerView", Integer.toString(i53, 36));
        Map<String, String> map54 = a;
        int i54 = b;
        b = i54 + 1;
        map54.put("RouteLineView", Integer.toString(i54, 36));
        Map<String, String> map55 = a;
        int i55 = b;
        b = i55 + 1;
        map55.put("ActionSheet", Integer.toString(i55, 36));
        Map<String, String> map56 = a;
        int i56 = b;
        b = i56 + 1;
        map56.put("GPSButtonNewMainPage", Integer.toString(i56, 36));
        Map<String, String> map57 = a;
        int i57 = b;
        b = i57 + 1;
        map57.put("MsgBoxView", Integer.toString(i57, 36));
        Map<String, String> map58 = a;
        int i58 = b;
        b = i58 + 1;
        map58.put("CommonTips", Integer.toString(i58, 36));
        Map<String, String> map59 = a;
        int i59 = b;
        b = i59 + 1;
        map59.put("ChoosePointBottomBar", Integer.toString(i59, 36));
        Map<String, String> map60 = a;
        int i60 = b;
        b = i60 + 1;
        map60.put("IphoneTreeView", Integer.toString(i60, 36));
        Map<String, String> map61 = a;
        int i61 = b;
        b = i61 + 1;
        map61.put("MvpGifImageView", Integer.toString(i61, 36));
        Map<String, String> map62 = a;
        int i62 = b;
        b = i62 + 1;
        map62.put("MsgBoxIconView", Integer.toString(i62, 36));
        Map<String, String> map63 = a;
        int i63 = b;
        b = i63 + 1;
        map63.put("SearchKeywordResultTitleView", Integer.toString(i63, 36));
        Map<String, String> map64 = a;
        int i64 = b;
        b = i64 + 1;
        map64.put("CursorEditText", Integer.toString(i64, 36));
        Map<String, String> map65 = a;
        int i65 = b;
        b = i65 + 1;
        map65.put("NumeralKeyBoardDriveView", Integer.toString(i65, 36));
        Map<String, String> map66 = a;
        int i66 = b;
        b = i66 + 1;
        map66.put("TabView", Integer.toString(i66, 36));
        Map<String, String> map67 = a;
        int i67 = b;
        b = i67 + 1;
        map67.put("MineView", Integer.toString(i67, 36));
        Map<String, String> map68 = a;
        int i68 = b;
        b = i68 + 1;
        map68.put("RingProgressBar", Integer.toString(i68, 36));
        Map<String, String> map69 = a;
        int i69 = b;
        b = i69 + 1;
        map69.put("View", Integer.toString(i69, 36));
        Map<String, String> map70 = a;
        int i70 = b;
        b = i70 + 1;
        map70.put("CircleImage11", Integer.toString(i70, 36));
        Map<String, String> map71 = a;
        int i71 = b;
        b = i71 + 1;
        map71.put("RadioButton", Integer.toString(i71, 36));
        Map<String, String> map72 = a;
        int i72 = b;
        b = i72 + 1;
        map72.put("Suspend11DefaultTemplate", Integer.toString(i72, 36));
        Map<String, String> map73 = a;
        int i73 = b;
        b = i73 + 1;
        map73.put("FeedbackDescriptionTextInput11", Integer.toString(i73, 36));
        Map<String, String> map74 = a;
        int i74 = b;
        b = i74 + 1;
        map74.put("ContactInputRow", Integer.toString(i74, 36));
        Map<String, String> map75 = a;
        int i75 = b;
        b = i75 + 1;
        map75.put("FeedbackAddPhoto11", Integer.toString(i75, 36));
        Map<String, String> map76 = a;
        int i76 = b;
        b = i76 + 1;
        map76.put("ClearableEditText", Integer.toString(i76, 36));
        Map<String, String> map77 = a;
        int i77 = b;
        b = i77 + 1;
        map77.put("SlidingUpPanelLayout", Integer.toString(i77, 36));
        Map<String, String> map78 = a;
        int i78 = b;
        b = i78 + 1;
        map78.put("RouteBusResultDetail11", Integer.toString(i78, 36));
        Map<String, String> map79 = a;
        int i79 = b;
        b = i79 + 1;
        map79.put("AmapButton", Integer.toString(i79, 36));
        Map<String, String> map80 = a;
        int i80 = b;
        b = i80 + 1;
        map80.put("SelectTimeRow", Integer.toString(i80, 36));
        Map<String, String> map81 = a;
        int i81 = b;
        b = i81 + 1;
        map81.put("Route11Group", Integer.toString(i81, 36));
        Map<String, String> map82 = a;
        int i82 = b;
        b = i82 + 1;
        map82.put("MapLocationInputRow", Integer.toString(i82, 36));
        Map<String, String> map83 = a;
        int i83 = b;
        b = i83 + 1;
        map83.put("ChooseFixPoint11", Integer.toString(i83, 36));
        Map<String, String> map84 = a;
        int i84 = b;
        b = i84 + 1;
        map84.put("TextInputRow", Integer.toString(i84, 36));
        Map<String, String> map85 = a;
        int i85 = b;
        b = i85 + 1;
        map85.put("Input", Integer.toString(i85, 36));
        Map<String, String> map86 = a;
        int i86 = b;
        b = i86 + 1;
        map86.put("Container", Integer.toString(i86, 36));
        Map<String, String> map87 = a;
        int i87 = b;
        b = i87 + 1;
        map87.put("AmapAjxView", Integer.toString(i87, 36));
        Map<String, String> map88 = a;
        int i88 = b;
        b = i88 + 1;
        map88.put("AjxAbsoluteLayout", Integer.toString(i88, 36));
        Map<String, String> map89 = a;
        int i89 = b;
        b = i89 + 1;
        map89.put("ExpandableListView", Integer.toString(i89, 36));
        Map<String, String> map90 = a;
        int i90 = b;
        b = i90 + 1;
        map90.put("SaveSearchTipView", Integer.toString(i90, 36));
        Map<String, String> map91 = a;
        int i91 = b;
        b = i91 + 1;
        map91.put("PoiTipView", Integer.toString(i91, 36));
    }
}
