package android.support.constraint.solver;

import java.util.ArrayList;

public class Metrics {
    public long A;
    public long B;
    public ArrayList<String> C = new ArrayList<>();
    public long D;
    public long a;
    public long b;
    public long c;
    public long d;
    public long e;
    public long f;
    public long g;
    public long h;
    public long i;
    public long j;
    public long k;
    public long l;
    public long m;
    public long n;
    public long o;
    public long p;
    public long q;
    public long r;
    public long s;
    public long t;
    public long u;
    public long v;
    public long w;
    public long x;
    public long y;
    public long z;

    public String toString() {
        StringBuilder sb = new StringBuilder("\n*** Metrics ***\nmeasures: ");
        sb.append(this.a);
        sb.append("\nadditionalMeasures: ");
        sb.append(this.b);
        sb.append("\nresolutions passes: ");
        sb.append(this.c);
        sb.append("\ntable increases: ");
        sb.append(this.d);
        sb.append("\nmaxTableSize: ");
        sb.append(this.p);
        sb.append("\nmaxVariables: ");
        sb.append(this.u);
        sb.append("\nmaxRows: ");
        sb.append(this.v);
        sb.append("\n\nminimize: ");
        sb.append(this.e);
        sb.append("\nminimizeGoal: ");
        sb.append(this.t);
        sb.append("\nconstraints: ");
        sb.append(this.f);
        sb.append("\nsimpleconstraints: ");
        sb.append(this.g);
        sb.append("\noptimize: ");
        sb.append(this.h);
        sb.append("\niterations: ");
        sb.append(this.i);
        sb.append("\npivots: ");
        sb.append(this.j);
        sb.append("\nbfs: ");
        sb.append(this.k);
        sb.append("\nvariables: ");
        sb.append(this.l);
        sb.append("\nerrors: ");
        sb.append(this.m);
        sb.append("\nslackvariables: ");
        sb.append(this.n);
        sb.append("\nextravariables: ");
        sb.append(this.o);
        sb.append("\nfullySolved: ");
        sb.append(this.q);
        sb.append("\ngraphOptimizer: ");
        sb.append(this.r);
        sb.append("\nresolvedWidgets: ");
        sb.append(this.s);
        sb.append("\noldresolvedWidgets: ");
        sb.append(this.A);
        sb.append("\nnonresolvedWidgets: ");
        sb.append(this.B);
        sb.append("\ncenterConnectionResolved: ");
        sb.append(this.w);
        sb.append("\nmatchConnectionResolved: ");
        sb.append(this.x);
        sb.append("\nchainConnectionResolved: ");
        sb.append(this.y);
        sb.append("\nbarrierConnectionResolved: ");
        sb.append(this.z);
        sb.append("\nproblematicsLayouts: ");
        sb.append(this.C);
        sb.append("\n");
        return sb.toString();
    }
}
