package com.alipay.mobile.common.transport.httpdns;

public enum ThreadType {
    HTTPDNSREQUEST_INIT,
    HTTPDNSREQUEST_NEWADD,
    HTTPDNSREQUEST_TIMEOUT,
    HTTPDNSREQUEST_NETWORKCHANGE,
    HTTPDNSFILE_READ,
    HTTPDNSFILE_WRITE,
    SYSTEMDNSTEST,
    SYSTEMHTTPTEST
}
